### ISSUE TITLE
Automatically update container images

### ISSUE THREAD

**Issue by zeroalphat** [cybozu/ubuntu-base#90]
## What

To update container images for security compliance, we need to create and merge PRs. 
However, it can be a labor-intensive process to perform those tasks in order to update container images.
It is necessary to be able to automate container image updates.

## How

Perform a vulnerability scan of container images using Trivy.
Using renovate, update container images that need to be updated based on the vulnerability scan results.

ref. https://github.com/cybozu-private/sgre-apps/blob/stage/.github/workflows/trivy.yml

## Checklist

- [ ] Finish implentation of the issue
- [ ] Test all functions
- [ ] Notify developers of necessary actions

**Comment by zoetrope** [comment]
https://github.com/cybozu-private/sgre-apps/blob/stage/.github/workflows/container-age-check.yml
